### ISSUE TITLE
An error occurs when I run "hetero_neighbor.py" in benchmark\sampler

### ISSUE THREAD

**Issue by Gibyeng** [pyg-team/pyg-lib#292]
### 🐛 Describe the bug

I ran the hetero_neighbor.py in command line without changing any code, but I got this error.
```
Traceback (most recent call last):
  File "/home/xxx/Documents/pyg-lib/benchmark/sampler/hetero_neighbor.py", line 146, in <module>
    test_hetero_neighbor()
  File "/home/xxx/anaconda3/envs/pyG-env/lib/python3.11/site-packages/pyg_lib/testing.py", line 17, in wrapper
    func(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/pyG-env/lib/python3.11/site-packages/pyg_lib/testing.py", line 65, in wrapper
    func(*args, dataset=dataset, **kwargs)
  File "/home/xxx/Documents/pyg-lib/benchmark/sampler/hetero_neighbor.py", line 91, in test_hetero_neighbor
    pyg_lib.sampler.hetero_neighbor_sample(
TypeError: hetero_neighbor_sample() got an unexpected keyword argument 'edge_time_dict'
```

### Environment

* `pyg-lib` version: 0.3
* PyTorch version: 2.1.0
* OS: ubuntu
* Python version: 3.11.5
* CUDA/cuDNN version: cuda_11.8
* How you installed PyTorch and `pyg-lib` (`conda`, `pip`, source): install pytorch by 'conda' but pyg-lib by 'pip' 
* Any other relevant information:

**Comment by Gibyeng** [comment]
I fixed this issue by reinstalling the pyg-lib from source. 
It works fine to me now.
