### ISSUE TITLE
failed to install pyg-lib on aarch64 ubuntu 20.04

### ISSUE THREAD

**Issue by richgrove** [pyg-team/pyg-lib#306]
### 🐛 Describe the bug

Run the installation:

`
$ pip3 install pyg-lib -f https://data.pyg.org/whl/torch-2.0.0+cu118.html
Looking in links: https://data.pyg.org/whl/torch-2.0.0+cu118.html
ERROR: Could not find a version that satisfies the requirement pyg-lib (from versions: none)
ERROR: No matching distribution found for pyg-lib
`

This is on **Arm64**.   The PyTorch 2.0.0 installed with Cuda 11.8 works fine.  If it's not supported, please add it as a feature request. Thanks.

### Environment

* `pyg-lib` version:
* PyTorch version:
* OS: ubuntu 20.04 arm64
* Python version: 3.8
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and `pyg-lib` (`conda`, `pip`, source): pip3 install torch-2.0.0+nv23.05-cp38-cp38-linux_aarch64.whl
* Any other relevant information:

**Comment by richgrove** [comment]
Here are the error messages when ran:

**$ pip3 install git+https://github.com/pyg-team/pyg-lib.git**

Collecting git+https://github.com/pyg-team/pyg-lib.git
  Cloning https://github.com/pyg-team/pyg-lib.git to /tmp/pip-req-build-7trih_7i
  Running command git clone --filter=blob:none --quiet https://github.com/pyg-team/pyg-lib.git /tmp/pip-req-build-7trih_7i
  Resolved https://github.com/pyg-team/pyg-lib.git to commit f90a23169779fc372a94f0b8bcd424890a9bdd35
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyg-lib
  Building wheel for pyg-lib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [244 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-38
      creating build/lib.linux-aarch64-cpython-38/pyg_lib
      copying pyg_lib/_triton.py -> build/lib.linux-aarch64-cpython-38/pyg_lib
      copying pyg_lib/__init__.py -> build/lib.linux-aarch64-cpython-38/pyg_lib
      copying pyg_lib/testing.py -> build/lib.linux-aarch64-cpython-38/pyg_lib
      copying pyg_lib/home.py -> build/lib.linux-aarch64-cpython-38/pyg_lib
      creating build/lib.linux-aarch64-cpython-38/pyg_lib/ops
      copying pyg_lib/ops/__init__.py -> build/lib.linux-aarch64-cpython-38/pyg_lib/ops
      copying pyg_lib/ops/scatter_reduce.py -> build/lib.linux-aarch64-cpython-38/pyg_lib/ops
      creating build/lib.linux-aarch64-cpython-38/pyg_lib/partition
      copying pyg_lib/partition/__init__.py -> build/lib.linux-aarch64-cpython-38/pyg_lib/partition
      creating build/lib.linux-aarch64-cpython-38/pyg_lib/sampler
      copying pyg_lib/sampler/__init__.py -> build/lib.linux-aarch64-cpython-38/pyg_lib/sampler
      running build_ext

      -- The C compiler identification is GNU 11.4.0
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Python3: /xxxx/anaconda3/envs/dev/include/python3.8 (found version "3.8.18") found components: Development Development.Module Development.Embed
      -- The CUDA compiler identification is NVIDIA 11.8.89
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Looking for execinfo.h
      -- Looking for execinfo.h - found
      -- Looking for getline
      -- Looking for getline - found
      -- Found CUDA: /usr/local/cuda (found version "11.8")
      -- Caffe2: CUDA detected: 11.8
      -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
      -- Caffe2: CUDA toolkit directory: /usr/local/cuda
      -- Caffe2: Header version is: 11.8
      -- /usr/local/cuda/lib64/libnvrtc.so shorthash is cb86903b
      -- USE_CUDNN is set to 0. Compiling without cuDNN support
      -- Autodetected CUDA architecture(s):  8.7
      -- Added CUDA NVCC flags for: -gencode;arch=compute_87,code=sm_87
      -- Found Torch: /xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/torch/lib/libtorch.so
      -- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
      -- Found OpenMP_CXX: -fopenmp (found version "4.5")
      -- Could NOT find OpenMP (missing: OpenMP_C_FOUND) (found version "4.5")
      -- CMAKE_BUILD_TYPE: RELEASE
      -- CMAKE_CXX_FLAGS_DEBUG: -g -O0
      -- CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
      -- Configuring done (9.6s)
      CMake Warning (dev) in CMakeLists.txt:
        Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
        empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
        for policy details.  Use the cmake_policy command to set the policy and
        suppress this warning.
     
        CUDA_ARCHITECTURES is empty for target pyg
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      CMake Warning at CMakeLists.txt:55 (add_library):
        Cannot generate a safe runtime search path for target pyg because files in
        some directories may conflict with libraries in implicit directories:
      
          runtime library [libgomp.so.1] in /usr/lib/gcc/aarch64-linux-gnu/11 may be hidden by files in:
            /xxxx/anaconda3/envs/dev/lib
      
        Some of these libraries may not be found correctly.
      
      
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-req-build-7trih_7i/build/temp.linux-aarch64-cpython-38
      [1/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/library.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      In file included from /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/library.cpp:1:
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/library.h:12:37: warning: ‘_register_ops’ initialized and declared ‘extern’
         12 | extern "C" PYG_INLINE_VARIABLE auto _register_ops = &cuda_version;
            |                                     ^~~~~~~~~~~~~
      [2/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/cpu/sampled_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [3/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/cpu/index_sort_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [4/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/cpu/softmax_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [5/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/cpu/matmul_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [6/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/index_sort.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [7/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/autograd/softmax_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [8/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/autograd/sampled_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [9/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/autograd/matmul_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [10/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/random/cpu/biased_sampling.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [11/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/sampled.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [12/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/partition/cpu/metis_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [13/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/partition/metis.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [14/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/softmax.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [15/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/matmul.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [16/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/cpu/dist_merge_outputs_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/dist_merge_outputs_kernel.cpp: In function std::tuple<at::Tensor, at::Tensor, c10::optional<at::Tensor>, std::vector<long int, std::allocator<long int> > > pyg::sampler::merge_sampler_outputs_kernel(const std::vector<at::Tensor>&, const std::vector<at::Tensor>&, const std::vector<std::vector<long int> >&, const std::vector<long int>&, const std::vector<long int>&, int64_t, int64_t, const c10::optional<at::Tensor>&, bool):
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/dist_merge_outputs_kernel.cpp:159:1: warning: control reaches end of non-void function [-Wreturn-type]
        159 | }
            | ^
      [17/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/cpu/random_walk_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [18/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/dist_merge_outputs.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [19/92] Building CUDA object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/cuda/sampled_kernel.cu.o
      [20/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/cpu/subgraph_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [21/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/dist_relabel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [22/92] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o
      FAILED: third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o
      /usr/bin/cc -DUSE_PYTHON -DWITH_CUDA -I/tmp/pip-req-build-7trih_7i/third_party/cutlass/include -I/tmp/pip-req-build-7trih_7i/third_party/cutlass/tools/util/include -I/tmp/pip-req-build-7trih_7i/third_party/METIS/GKlib -I/tmp/pip-req-build-7trih_7i/third_party/METIS/include -I/tmp/pip-req-build-7trih_7i/third_party/METIS/libmetis/. -DIDXTYPEWIDTH=64 -DREALTYPEWIDTH=32 -DLINUX -D_FILE_OFFSET_BITS=64 -std=c99 -fno-strict-aliasing -march=native -fPIC -Werror -Wall -pedantic -Wno-unused-function -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unknown-pragmas -Wno-unused-label -DNDEBUG -DNDEBUG2 -DHAVE_EXECINFO_H -DHAVE_GETLINE -O3 -O3 -DNDEBUG -MD -MT third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o -MF third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o.d -o third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o -c /tmp/pip-req-build-7trih_7i/third_party/METIS/GKlib/b64.c
      Assembler messages:
      Error: unknown architectural extension flagm
      Error: unrecognized option -march=armv8.2-a+crypto+fp16+rcpc+dotprod+flagm
      [23/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/neighbor.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [24/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/random_walk.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [25/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/utils/check.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [26/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/utils/convert.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [27/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/subgraph.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      [28/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/cpu/dist_relabel_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/dist_relabel_kernel.cpp: In function ‘std::tuple<at::Tensor, at::Tensor> pyg::sampler::relabel_neighborhood_kernel(const at::Tensor&, const at::Tensor&, const std::vector<long int>&, int64_t, const c10::optional<at::Tensor>&, bool, bool)’:
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/dist_relabel_kernel.cpp:290:1: warning: control reaches end of non-void function [-Wreturn-type]
        290 | }
            | ^
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/dist_relabel_kernel.cpp: In function ‘std::tuple<c10::Dict<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor>, c10::Dict<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor> > pyg::sampler::hetero_relabel_neighborhood_kernel(const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, const c10::Dict<std::__cxx11::basic_string<char>, at::Tensor>&, const c10::Dict<std::__cxx11::basic_string<char>, at::Tensor>&, const c10::Dict<std::__cxx11::basic_string<char>, std::vector<std::vector<long int> > >&, const c10::Dict<std::__cxx11::basic_string<char>, long int>&, const c10::optional<c10::Dict<std::__cxx11::basic_string<char>, at::Tensor> >&, bool, bool)’:
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/dist_relabel_kernel.cpp:309:1: warning: control reaches end of non-void function [-Wreturn-type]
        309 | }
            | ^
      [29/92] Building CUDA object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/cuda/random_walk_kernel.cu.o
      [30/92] Building CUDA object CMakeFiles/pyg.dir/pyg_lib/csrc/ops/cuda/matmul_kernel.cu.o
      [31/92] Building CXX object CMakeFiles/pyg.dir/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp.o
      <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
      <command-line>: note: this is the location of the previous definition
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp: In lambda function:
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp:917:3: warning: control reaches end of non-void function [-Wreturn-type]
        917 |   }();
            |   ^
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp: In function ‘std::tuple<c10::Dict<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor>, c10::Dict<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor>, c10::Dict<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor>, c10::optional<c10::Dict<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, at::Tensor> >, c10::Dict<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<long int, std::allocator<long int> > >, c10::Dict<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<long int, std::allocator<long int> > > > pyg::sampler::hetero_neighbor_sample_kernel(const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, const c10::Dict<std::__cxx11::basic_string<char>, at::Tensor>&, const c10::Dict<std::__cxx11::basic_string<char>, at::Tensor>&, const c10::Dict<std::__cxx11::basic_string<char>, at::Tensor>&, const c10::Dict<std::__cxx11::basic_string<char>, std::vector<long int> >&, const c10::optional<c10::Dict<std::__cxx11::basic_string<char>, at::Tensor> >&, const c10::optional<c10::Dict<std::__cxx11::basic_string<char>, at::Tensor> >&, const c10::optional<c10::Dict<std::__cxx11::basic_string<char>, at::Tensor> >&, const c10::optional<c10::Dict<std::__cxx11::basic_string<char>, at::Tensor> >&, bool, bool, bool, bool, std::string, bool)’:
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp:949:1: warning: control reaches end of non-void function [-Wreturn-type]
        949 | }
            | ^
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp: In lambda function:
      /tmp/pip-req-build-7trih_7i/pyg_lib/csrc/sampler/cpu/neighbor_kernel.cpp:969:3: warning: control reaches end of non-void function [-Wreturn-type]
        969 |   }();
            |   ^
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-7trih_7i/setup.py", line 129, in <module>
          setup(
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-req-build-7trih_7i/setup.py", line 84, in build_extension
          subprocess.check_call(['cmake', '--build', '.'] + build_args,
        File "/xxxx/anaconda3/envs/dev/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyg-lib
  Running setup.py clean for pyg-lib
Failed to build pyg-lib
ERROR: Could not build wheels for pyg-lib, which is required to install pyproject.toml-based projects
`

**Comment by rusty1s** [comment]
This looks to be an issue related to `CUTLASS`, not yet sure how to fix this on our end (cc @puririshi98). In the worst case, try to install via `FORCE_CUDA=0 pip install ...`

**Comment by akihironitta** [comment]
For anyone seeing this issue, `pyg-lib==0.8.0` started shipping with aarch64 wheels, and users should no longer need to install `pyg-lib` from source for most cases.
